server:
  port: 8084
spring:
  profiles: dev
  application:
    name: abcmsc-provider-depart



  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test02?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8400/eureka
---
server:
  port: 8085
spring:
  profiles: test
  application:
    name: abcmsc-provider-depart



  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test03?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8500/eureka
